// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlmfY0dXE1-7nHiAmox7YMRk7aGYN53I8',
    appId: '1:412015995434:web:47e19b6852e4c6440c3153',
    messagingSenderId: '412015995434',
    projectId: 'can-care-de0aa',
    authDomain: 'can-care-de0aa.firebaseapp.com',
    storageBucket: 'can-care-de0aa.appspot.com',
    measurementId: 'G-K10XMTMHXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdKv6PZ_siP2SI19CtjtVUHEdTINN9OG4',
    appId: '1:412015995434:android:5b1c010d0bd3025c0c3153',
    messagingSenderId: '412015995434',
    projectId: 'can-care-de0aa',
    storageBucket: 'can-care-de0aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwFJo4sdwt0FyOo2gPlm-ha1t-1t9mt4w',
    appId: '1:412015995434:ios:42cc4bbe02fb1feb0c3153',
    messagingSenderId: '412015995434',
    projectId: 'can-care-de0aa',
    storageBucket: 'can-care-de0aa.appspot.com',
    iosBundleId: 'co.can.care',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwFJo4sdwt0FyOo2gPlm-ha1t-1t9mt4w',
    appId: '1:412015995434:ios:42cc4bbe02fb1feb0c3153',
    messagingSenderId: '412015995434',
    projectId: 'can-care-de0aa',
    storageBucket: 'can-care-de0aa.appspot.com',
    iosBundleId: 'co.can.care',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlmfY0dXE1-7nHiAmox7YMRk7aGYN53I8',
    appId: '1:412015995434:web:47e19b6852e4c6440c3153',
    messagingSenderId: '412015995434',
    projectId: 'can-care-de0aa',
    authDomain: 'can-care-de0aa.firebaseapp.com',
    storageBucket: 'can-care-de0aa.appspot.com',
    measurementId: 'G-K10XMTMHXR',
  );

}